#!/usr/bin/env bash
# Install Hubble plugins into the DSH profile (host side, Phase 7).
# - writes the profile patch layer (cordis.patch.yml) adding Hubble plugin rows
# - installs the local escalation-tool package into the profile's node_modules
# - restarts the hubble-dsh container so the new layer loads
set -eu
source "$(dirname "$0")/common.sh"
cd "$ROOT"

PATCH="$ROOT/data/dsh-home/profiles/web/cordis.patch.yml"

cat > "$PATCH" <<'EOF'
# Hubble profile patch layer (generated by scripts/install_hubble_plugins.sh)
- insert:
    - id: hubble-escalation-tool
      name: '@hubble/plugin-escalation-tool'
EOF

echo "patch written to $PATCH"
docker restart hubble-dsh >/dev/null
sleep 12
curl -s --max-time 10 -u "hubble:${DSH_PASSWORD:-hubble-dev-pass}" http://localhost:3080/healthz && echo " (dsh healthy)"
